// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzd6-DV7hWZvqPyikaSNK-s7DXMnIlAT0',
    appId: '1:513736227861:web:79c67203ffaa4de5a4e21c',
    messagingSenderId: '513736227861',
    projectId: 'balanced-craves',
    authDomain: 'balanced-craves.firebaseapp.com',
    storageBucket: 'balanced-craves.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBSKg8m1iumvmgqA1zHNFwFIRCFhIRJG0',
    appId: '1:513736227861:android:0712bfdfcc015728a4e21c',
    messagingSenderId: '513736227861',
    projectId: 'balanced-craves',
    storageBucket: 'balanced-craves.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfGIBuoAVEVGmsrj7Iub2JnsNQb2QFBk4',
    appId: '1:513736227861:ios:2974fce31360ffcaa4e21c',
    messagingSenderId: '513736227861',
    projectId: 'balanced-craves',
    storageBucket: 'balanced-craves.appspot.com',
    iosBundleId: 'com.example.balancedcraves',
  );
}
